In [1]:
import numpy as np
import pandas as pd

In [2]:
print("Experiment-1")

arr = np.array([1, 2, 3, 4, 5])

print("Array:", arr)
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)

print("\n")

Experiment-1
Array: [1 2 3 4 5]
Shape: (5,)
Data Type: int64




In [3]:
print("Experiment-2")

zeros_matrix = np.zeros((3, 4))
ones_matrix = np.ones((2, 5))

print("Zeros Matrix:\n", zeros_matrix)
print("Shape:", zeros_matrix.shape)

print("\nOnes Matrix:\n", ones_matrix)
print("Shape:", ones_matrix.shape)

print("\n")

Experiment-2
Zeros Matrix:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4)

Ones Matrix:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Shape: (2, 5)




In [4]:
print("Experiment-3")

arr = np.arange(1, 13)

reshaped_arr = arr.reshape(3, 4)

print("Original Array:", arr)
print("Shape:", arr.shape)

print("\nReshaped Array:\n", reshaped_arr)
print("Shape:", reshaped_arr.shape)

print("\n")

Experiment-3
Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)

Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)




In [5]:
print("Experiment-4")

random_arr = np.random.randint(1, 100, 10)

print("Array:", random_arr)
print("Minimum:", np.min(random_arr))
print("Maximum:", np.max(random_arr))
print("Mean:", np.mean(random_arr))
print("Sum:", np.sum(random_arr))

print("\n")

Experiment-4
Array: [38 74 45 10 12 33 59 70  3 38]
Minimum: 3
Maximum: 74
Mean: 38.2
Sum: 382




In [6]:
print("Experiment-5")

data = {
    "Name": ["Aman", "Riya", "Rahul", "Sneha"],
    "Marks": [85, 90, 78, 92]
}

df = pd.DataFrame(data)

print("DataFrame:\n", df)
print("\nData Types:\n", df.dtypes)

print("\n")


Experiment-5
DataFrame:
     Name  Marks
0   Aman     85
1   Riya     90
2  Rahul     78
3  Sneha     92

Data Types:
 Name     object
Marks     int64
dtype: object




In [8]:
import pandas as pd
print("Experiment-6")

# Upload CSV in Colab first OR use sample dataset
df_csv = pd.read_csv("/content/Iris.csv")  # change file name if needed

print("First 5 rows:\n", df_csv.head())
print("\nLast 5 rows:\n", df_csv.tail())

print("\n")

Experiment-6
First 5 rows:
    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

Last 5 rows:
       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iri

In [9]:
print("Experiment-7")

print(df_csv.info())

print("\nRows and Columns:", df_csv.shape)

print("\nMissing Values:\n", df_csv.isnull().sum())

print("\n")


Experiment-7
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB
None

Rows and Columns: (150, 6)

Missing Values:
 Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64




In [10]:
print("Experiment-8")

print(df_csv.describe())

# Interpretation (for viva)
print("\nInterpretation:")
print("Mean = Average value")
print("Std = Spread of data")
print("Min = Smallest value")
print("Max = Largest value")

Experiment-8
               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

Interpretation:
Mean = Average value
Std = Spread of data
Min = Smallest value
Max = Largest value
